### ISSUE TITLE
Consider creating a root-level OWNERS file

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/compute-image-packages#859]
Example such file: https://github.com/GoogleCloudPlatform/testgrid/blob/master/OWNERS

Does this repo use tide?

If you do you can have prow's blunderbuss auto-assign PRs for people to review

```yaml
{
 insertId: "hhe0klg19qto38"  
 jsonPayload: {
  author: "hopkiw"   
  component: "hook"   
  event-GUID: "fabaa5a0-eabf-11e9-9d1c-e83845a44c3d"   
  event-type: "pull_request"   
  file: "prow/plugins/approve/approvers/owners.go:164"   
  func: "k8s.io/test-infra/prow/plugins/approve/approvers.Owners.GetSuggestedApprovers"   
  level: "warning"   
  msg: "Couldn't find/suggest approvers for each files. Unapproved: [""]"   
  org: "GoogleCloudPlatform"   
  plugin: "approve"   
  pr: 858   
  repo: "compute-image-packages"   
  url: "https://github.com/GoogleCloudPlatform/compute-image-packages/pull/858"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/hook"  
 receiveTimestamp: "2019-10-09T18:09:53.708324141Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-09T18:09:52Z"  
}
```

**Comment by hopkiw** [comment]
this is a legacy repo that we've done some prow testing with; the entire repo is slated for deprecation. you can feel free to set up a sync on our use of prow if you'd like to consolidate your feedback

**Comment by fejta** [comment]
/assign @illfelder @hopkiw 

Will one of you please create a root OWNERS file? See https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md for what this looks like (or the link to a concrete example in the desc)

```yaml
{
 insertId: "506i77g1eg0aw9"  
 jsonPayload: {
  author: "illfelder"   
  component: "hook"   
  event-GUID: "b3666c00-17a8-11ea-80f2-bff4cf51329d"   
  event-type: "pull_request"   
  file: "prow/plugins/approve/approvers/owners.go:164"   
  func: "k8s.io/test-infra/prow/plugins/approve/approvers.Owners.GetSuggestedApprovers"   
  level: "warning"   
  msg: "Couldn't find/suggest approvers for each files. Unapproved: [""]"   
  org: "GoogleCloudPlatform"   
  plugin: "approve"   
  pr: 876   
  repo: "compute-image-packages"   
  url: "https://github.com/GoogleCloudPlatform/compute-image-packages/pull/876"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/hook"  
 receiveTimestamp: "2019-12-05T21:46:38.824663700Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-05T21:46:35Z"  
}
```
